Added added country and region ISO code properties
gietos/dadata pull request #43
Opened 2020-03-10 11:58 UTC by AndreyProkofyev

2020-03-10 13:32 UTC, kstkn requested changes
Thanks for the PR!
Can you please clean up extra stuff added during development? Like package name change and additional dev package requirement.

2020-03-11 04:52 UTC, AndreyProkofyev commented
> Thanks for the PR!
> Can you please clean up extra stuff added during development? Like package name change and additional dev package requirement.

Done

2020-03-11 06:13 UTC, kstkn approved these changes

2020-03-11 06:13 UTC, merged

2020-03-11 07:23 UTC, kstkn commented
Just for your information. This was created from master and merged to master. This doesn't affect v1.1.*. To have it there, changes should be applied to `1.1` branch.